### ISSUE TITLE
Limit refresh rate by default

### ISSUE THREAD

**Issue by janvorisek** [bumbu/svg-pan-zoom#351]
I am using the plugin to manipulate SVG containing ~100 elements which I don't think is a lot. The performance (of dragging) is great on FHD resolution. However, it degrades dramatically on higher (4k) resolution. By degraded performance i mean the dragged content lags behind the cursor.

To fix the issue I am currently using a fixed **refreshRate** of 30 and panning feels smooth even on high resolutions.

**Comment by ethubert** [comment]
The implementation of refresh rate in this library is great IMO, it doesn't need changing. 
You say yourself you could set your refresh rate yourself. For me a refresh rate of 60Hz was spot on.

Code for those who couldn't find how to set refreshRate
` //Initializing library for manipulation ( pan and zoom ) of svg graph
  const svgCommands = svgPanZoom(graphSVG, {
    zoomScaleSensitivity: 1,
    maxZoom: 30,
    refreshRate: 60
  });`

**Comment by ariutta** [comment]
It would be necessary to look at some combination of number of elements in the SVG, the size and resolution of the display, etc.
