### ISSUE TITLE
Maintenance plan

### ISSUE THREAD

**Issue by ariutta** [bumbu/svg-pan-zoom#395]
Hi collaborators,

Are any of you interested in taking over this project? My job has shifted focus away from front-end, so I'm not able to keep up with maintenance. I'd be happy to transfer this repo and the NPM package to one of you.

@aleofreddi originally created the script to be used inside an SVG. I modified that script so it would work from the HTML. @bumbu made many valuable improvements and is by far the top committer. @timelyportfolio made it work with R.

If any of you would like to take over, let me know. If not, I'm open to transferring it to anyone else with a track record of trustworthy contributions to open source projects.

@aleofreddi, @bumbu, @jacobwindsor, @timelyportfolio, @Yimiprod

**Comment by bumbu** [comment]
Hi @ariutta, long time no see!

I'd love to take over this project as you know that I contributed quite a bit to it. At the same time I tried few times in the past few years to come back to it and contribute something significant, and failed to last long. So I wouldn't be a good owner for it if there are other passionate people.

That said, if no one else is interested in driving it, and the only other alternative is for this project to die - I'm happy to take over it to keep the continuity.

**Comment by ariutta** [comment]
Hi @bumbu! I hope everything is going well with you! I'll send you a transfer request.

**Comment by ariutta** [comment]
I tried transferring, but I got an error, because there's already a repo named bumbu/svg-pan-zoom. If you can delete that repo, I can transfer this one over to you so that bumbu/svg-pan-zoom is the main repo.

More info:
https://docs.github.com/en/github/administering-a-repository/transferring-a-repository

**Comment by bumbu** [comment]
Hey @ariutta 
I deleted the fork from my account. Let me know if it helped

**Comment by ariutta** [comment]
That worked. It now says: "Repository transfer to bumbu requested," so I think you just need to accept the request and the transfer will be complete. Thanks for all the work you've put into this over the years!

**Comment by bumbu** [comment]
I accepted it and the transfer seems to be working fine. Thanks for taking care of the library continuity!
