### ISSUE TITLE
Zoom to fit the selection

### ISSUE THREAD

**Issue by leoheck** [bumbu/svg-pan-zoom#401]
Hey @ariutta, quick question. Is it possible to make zoom fit the selection? Do you have any examples of this?

**Comment by wassfila** [comment]
There is already a function to zoom on the dbl clicked area enabled with the parameter `dblClickZoomEnabled: true`
Is that what you're looking for ? Cause I don't think you can select the text in the SVG no ?
Or maybe you'd like to give a text as argument and have the SVG zoom into it ? Cause that's actually what I developed here, and even with a CSS transition zoom and animated svg morphology filter to highlight the text
https://www.homesmartmesh.com/docs/microcontrollers/nrf52/thread_sensortag/?svg=nrf52-sensor-tag&text=VEML6030

![Deep-SVG-Link](https://user-images.githubusercontent.com/1510763/116909651-d074c800-ac44-11eb-8c32-5132982c1e52.gif)

**Comment by leoheck** [comment]
Hey @wassfila, what I wanted to do is to fit the zoom, by drawing an are with the mouse. Something like zoom to fit the selection.

**Comment by wassfila** [comment]
I see, then actually you might have to collect the mouse down and mouse up yourself and then take it from there to identify the zoom center and ratio.
You might have to deal with inconsistent aspect ratio of the selection not matching that of the viewport, so you could arbitrarily stick to the width, height or average.
I'm not aware that the library can do that out of the box, but maybe others know more. Would collecting mouse down and mouse up be feasible for you, and would you want to add a drawing of darker or highlight of the selected area ? Cause that's slowly becoming a tool dev which probably was not the scope of this but would be a cool feature.

**Comment by leoheck** [comment]
I will take a different route. Since you said it has to be used with a server I am going to find one to give it a try. Oh, I remember that in the past I was using this with a webserver created in python.
